### ISSUE TITLE
TypeError: Cannot read property 'userAgent' of undefined

### ISSUE THREAD

**Issue by alfonsoabad** [wright-io/givenwhenthen#13]
When running the examples ..

cake test:acceptance

/Users/alfonso/code/given/givenwhenthen/node_modules/open.core/node_modules/jquery/dist/node-jquery.js:92
    userAgent = navigator.userAgent,
                      ^
TypeError: Cannot read property 'userAgent' of undefined
  at /Users/alfonso/code/given/givenwhenthen/node_modules/open.core/node_modules/jquery/dist/node-jquery.js:92:23
  at module (/Users/alfonso/code/given/givenwhenthen/node_modules/open.core/node_modules/jquery/dist/node-jquery.js:964:2)
  at create (/Users/alfonso/code/given/givenwhenthen/node_modules/open.core/node_modules/jquery/dist/node-jquery.js:8996:2)
  at /Users/alfonso/code/given/givenwhenthen/node_modules/open.core/node_modules/jquery/dist/node-jquery.js:9000:18
  at Object.<anonymous> (/Users/alfonso/code/given/givenwhenthen/node_modules/open.core/node_modules/jquery/dist/node-jquery.js:9004:1)
  at Module._compile (module.js:446:26)
  at Object.Module._extensions..js (module.js:464:10)
  at Module.load (module.js:353:31)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:359:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/alfonso/code/given/givenwhenthen/node_modules/open.core/lib/src/server/config/libs.coffee:5:8)
  at Object.<anonymous> (/Users/alfonso/code/given/givenwhenthen/node_modules/open.core/lib/src/server/config/libs.coffee:36:4)
  at Module._compile (module.js:446:26)
  at Object.require.extensions..coffee (/Users/alfonso/code/given/givenwhenthen/node_modules/coffee-script/lib/coffee-script/coffee-script.js:30:21)
  at Module.load (module.js:353:31)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:359:17)
  at require (module.js:375:17)
  at /Users/alfonso/code/given/givenwhenthen/node_modules/open.core/lib/src/server/index.coffee:107:5
  at Object.<anonymous> (/Users/alfonso/code/given/givenwhenthen/node_modules/open.core/lib/src/server/index.coffee:118:4)
  at Object.<anonymous> (/Users/alfonso/code/given/givenwhenthen/node_modules/open.core/lib/src/server/index.coffee:120:4)
  at Module._compile (module.js:446:26)
  at Object.require.extensions..coffee (/Users/alfonso/code/given/givenwhenthen/node_modules/coffee-script/lib/coffee-script/coffee-script.js:30:21)
  at Module.load (module.js:353:31)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:359:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/alfonso/code/given/givenwhenthen/node_modules/open.core/index.js:3:18)
  at Module._compile (module.js:446:26)
  at Object.Module._extensions..js (module.js:464:10)
  at Module.load (module.js:353:31)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:359:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/alfonso/code/given/givenwhenthen/lib/acceptance.coffee:4:10)
  at Object.<anonymous> (/Users/alfonso/code/given/givenwhenthen/lib/acceptance.coffee:368:4)
  at Module._compile (module.js:446:26)
  at Object.require.extensions..coffee (/Users/alfonso/code/given/givenwhenthen/node_modules/coffee-script/lib/coffee-script/coffee-script.js:30:21)
  at Module.load (module.js:353:31)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:359:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/alfonso/code/given/givenwhenthen/index.js:2:25)
  at Module._compile (module.js:446:26)
  at Object.Module._extensions..js (module.js:464:10)
  at Module.load (module.js:353:31)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:359:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/alfonso/code/given/givenwhenthen/examples/Cakefile:1:1, <js>:4:19)
  at Object.<anonymous> (/Users/alfonso/code/given/givenwhenthen/examples/Cakefile:21:4)
  at Module._compile (module.js:446:26)

**Comment by wright-io** [comment]
I'm not able to duplicate this when running the examples as they are currently set up.  Can you provide reproduction steps?  If you just clone givenwhenthen, run `npm install`, cd to `/examples`, and run `cake test:acceptance`, do you get the same issue?

**Comment by wright-io** [comment]
Considering closed for now.  Please reopen with the requested details if you're still having the issue.  Thanks!
